export const MOCK_SEARCH_KEYWORDS = [
  "한식",
  "미슐랭 맛집",
  "대만인이 많이 찾는 맛집",
  "SNS 핫플레이스",
  "데이트 코스",
  "가성비 맛집",
];

export const MOCK_RESTAURANT_THEMES = [
  {
    id: 1,
    title: "미슐랭 가이드 선정 맛집",
    imageUrl: "https://picsum.photos/seed/michelin/400/300",
    slug: "michelin",
  },
  {
    id: 2,
    title: "SNS에서 인기 있는 맛집",
    imageUrl: "https://picsum.photos/seed/sns/400/300",
    slug: "sns",
  },
  {
    id: 3,
    title: "데이트하기 좋은 맛집",
    imageUrl: "https://picsum.photos/seed/date/400/300",
    slug: "date",
  },
  {
    id: 4,
    title: "현지인이 추천하는 맛집",
    imageUrl: "https://picsum.photos/seed/local/400/300",
    slug: "local",
  },
  {
    id: 5,
    title: "가성비 좋은 맛집",
    imageUrl: "https://picsum.photos/seed/value/400/300",
    slug: "value",
  },
  {
    id: 6,
    title: "대만인이 많이 찾는 맛집",
    imageUrl: "https://picsum.photos/seed/taiwan/400/300",
    slug: "taiwan",
  },
];

export interface Restaurant {
  id: number;
  name: string;
  category: string;
  rating: number;
  reviewCount: number;
  address: string;
  imageUrl: string;
  priceRange: string;
  operatingHours: string;
  isOpen: boolean;
  theme?: string;
}

export const MOCK_RESTAURANTS: Restaurant[] = [
  // 한식 (korean)
  {
    id: 1,
    name: "서울정식당",
    category: "korean",
    rating: 4.7,
    reviewCount: 312,
    address: "서울 종로구 인사동 789",
    imageUrl: "https://picsum.photos/seed/korean1/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },
  {
    id: 2,
    name: "궁중한정식",
    category: "korean",
    rating: 4.9,
    reviewCount: 458,
    address: "서울 종로구 삼청동 123",
    imageUrl: "https://picsum.photos/seed/korean2/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:30",
    isOpen: true,
  },
  {
    id: 3,
    name: "할매국밥",
    category: "korean",
    rating: 4.5,
    reviewCount: 221,
    address: "서울 중구 을지로 456",
    imageUrl: "https://picsum.photos/seed/korean3/400/300",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
  },
  {
    id: 4,
    name: "청와대 소불고기",
    category: "korean",
    rating: 4.8,
    reviewCount: 534,
    address: "서울 종로구 청운동 789",
    imageUrl: "https://picsum.photos/seed/korean4/400/300",
    priceRange: "₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
  },
  {
    id: 5,
    name: "평양냉면",
    category: "korean",
    rating: 4.6,
    reviewCount: 178,
    address: "서울 중구 명동 234",
    imageUrl: "https://picsum.photos/seed/korean5/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },

  // 중식 (chinese)
  {
    id: 6,
    name: "대만반점",
    category: "chinese",
    rating: 4.5,
    reviewCount: 95,
    address: "서울 마포구 연남동 456",
    imageUrl: "https://picsum.photos/seed/chinese1/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:30",
    isOpen: true,
  },
  {
    id: 7,
    name: "홍콩반점",
    category: "chinese",
    rating: 4.3,
    reviewCount: 167,
    address: "서울 서대문구 연희동 789",
    imageUrl: "https://picsum.photos/seed/chinese2/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 22:00",
    isOpen: true,
  },
  {
    id: 8,
    name: "취향관",
    category: "chinese",
    rating: 4.7,
    reviewCount: 423,
    address: "서울 중구 명동 567",
    imageUrl: "https://picsum.photos/seed/chinese3/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
  },
  {
    id: 9,
    name: "마라훠궈",
    category: "chinese",
    rating: 4.6,
    reviewCount: 312,
    address: "서울 마포구 상수동 890",
    imageUrl: "https://picsum.photos/seed/chinese4/400/300",
    priceRange: "₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
  },
  {
    id: 10,
    name: "딤섬하우스",
    category: "chinese",
    rating: 4.4,
    reviewCount: 178,
    address: "서울 강남구 신사동 123",
    imageUrl: "https://picsum.photos/seed/chinese5/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },

  // 일식 (japanese)
  {
    id: 11,
    name: "미도인 - 미슐랭 1스타",
    category: "japanese",
    rating: 4.8,
    reviewCount: 128,
    address: "서울 중구 을지로 123",
    imageUrl: "https://picsum.photos/seed/japanese1/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
  },
  {
    id: 12,
    name: "스시히로",
    category: "japanese",
    rating: 4.9,
    reviewCount: 245,
    address: "서울 강남구 청담동 456",
    imageUrl: "https://picsum.photos/seed/japanese2/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
  },
  {
    id: 13,
    name: "라멘베이스",
    category: "japanese",
    rating: 4.5,
    reviewCount: 567,
    address: "서울 마포구 합정동 789",
    imageUrl: "https://picsum.photos/seed/japanese3/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 21:30",
    isOpen: true,
  },
  {
    id: 14,
    name: "돈카츠 전문점",
    category: "japanese",
    rating: 4.6,
    reviewCount: 432,
    address: "서울 서초구 방배동 012",
    imageUrl: "https://picsum.photos/seed/japanese4/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },
  {
    id: 15,
    name: "우동야",
    category: "japanese",
    rating: 4.4,
    reviewCount: 198,
    address: "서울 송파구 잠실동 345",
    imageUrl: "https://picsum.photos/seed/japanese5/400/300",
    priceRange: "₩",
    operatingHours: "10:30 - 21:00",
    isOpen: true,
  },

  // 디저트 (dessert)
  {
    id: 16,
    name: "디저트 천국",
    category: "dessert",
    rating: 4.9,
    reviewCount: 445,
    address: "서울 강남구 신사동 567",
    imageUrl: "https://picsum.photos/seed/dessert1/400/300",
    priceRange: "₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
  },
  {
    id: 17,
    name: "마카롱 하우스",
    category: "dessert",
    rating: 4.7,
    reviewCount: 334,
    address: "서울 마포구 연남동 678",
    imageUrl: "https://picsum.photos/seed/dessert2/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },
  {
    id: 18,
    name: "초콜릿 카페",
    category: "dessert",
    rating: 4.8,
    reviewCount: 223,
    address: "서울 용산구 이태원동 890",
    imageUrl: "https://picsum.photos/seed/dessert3/400/300",
    priceRange: "₩₩",
    operatingHours: "12:00 - 21:00",
    isOpen: true,
  },
  {
    id: 19,
    name: "타르트 & 케이크",
    category: "dessert",
    rating: 4.6,
    reviewCount: 167,
    address: "서울 서초구 반포동 123",
    imageUrl: "https://picsum.photos/seed/dessert4/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 20:00",
    isOpen: true,
  },
  {
    id: 20,
    name: "젤라또 랩",
    category: "dessert",
    rating: 4.5,
    reviewCount: 198,
    address: "서울 종로구 삼청동 456",
    imageUrl: "https://picsum.photos/seed/dessert5/400/300",
    priceRange: "₩",
    operatingHours: "12:00 - 21:00",
    isOpen: true,
  },

  // 24시간 운영 (24-hours)
  {
    id: 21,
    name: "심야식당",
    category: "24-hours",
    rating: 4.4,
    reviewCount: 89,
    address: "서울 마포구 서교동 890",
    imageUrl: "https://picsum.photos/seed/24hours1/400/300",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
  },
  {
    id: 22,
    name: "올나잇 포차",
    category: "24-hours",
    rating: 4.3,
    reviewCount: 156,
    address: "서울 강남구 역삼동 234",
    imageUrl: "https://picsum.photos/seed/24hours2/400/300",
    priceRange: "₩₩",
    operatingHours: "24시간",
    isOpen: true,
  },
  {
    id: 23,
    name: "새벽집",
    category: "24-hours",
    rating: 4.5,
    reviewCount: 234,
    address: "서울 용산구 한남동 567",
    imageUrl: "https://picsum.photos/seed/24hours3/400/300",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
  },
  {
    id: 24,
    name: "야간식당",
    category: "24-hours",
    rating: 4.2,
    reviewCount: 167,
    address: "서울 중구 을지로 890",
    imageUrl: "https://picsum.photos/seed/24hours4/400/300",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
  },
  {
    id: 25,
    name: "밤하늘",
    category: "24-hours",
    rating: 4.6,
    reviewCount: 145,
    address: "서울 동대문구 청량리동 123",
    imageUrl: "https://picsum.photos/seed/24hours5/400/300",
    priceRange: "₩₩",
    operatingHours: "24시간",
    isOpen: true,
  },

  // 비건/채식 (vegan)
  {
    id: 26,
    name: "베지테리안",
    category: "vegan",
    rating: 4.6,
    reviewCount: 67,
    address: "서울 용산구 이태원동 234",
    imageUrl: "https://picsum.photos/seed/vegan1/400/300",
    priceRange: "₩₩₩",
    operatingHours: "10:00 - 22:00",
    isOpen: true,
  },
  {
    id: 27,
    name: "그린테이블",
    category: "vegan",
    rating: 4.7,
    reviewCount: 189,
    address: "서울 마포구 상수동 567",
    imageUrl: "https://picsum.photos/seed/vegan2/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
  },
  {
    id: 28,
    name: "로푸드 카페",
    category: "vegan",
    rating: 4.5,
    reviewCount: 134,
    address: "서울 강남구 청담동 890",
    imageUrl: "https://picsum.photos/seed/vegan3/400/300",
    priceRange: "₩₩",
    operatingHours: "09:00 - 20:00",
    isOpen: true,
  },
  {
    id: 29,
    name: "채식주의",
    category: "vegan",
    rating: 4.8,
    reviewCount: 223,
    address: "서울 서초구 방배동 123",
    imageUrl: "https://picsum.photos/seed/vegan4/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
  },
  {
    id: 30,
    name: "비건 키친",
    category: "vegan",
    rating: 4.4,
    reviewCount: 156,
    address: "서울 성동구 성수동 456",
    imageUrl: "https://picsum.photos/seed/vegan5/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 20:30",
    isOpen: true,
  },
];

export const MOCK_THEME_RESTAURANTS: Restaurant[] = [
  // 미슐랭 가이드 선정 맛집
  {
    id: 101,
    name: "스시 오마카세",
    category: "japanese",
    rating: 4.9,
    reviewCount: 521,
    address: "서울 강남구 청담동 123",
    imageUrl: "https://picsum.photos/seed/michelin1/400/300",
    priceRange: "₩₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "michelin",
  },
  {
    id: 102,
    name: "프렌치 다이닝",
    category: "western",
    rating: 4.8,
    reviewCount: 412,
    address: "서울 용산구 이태원동 456",
    imageUrl: "https://picsum.photos/seed/michelin2/400/300",
    priceRange: "₩₩₩",
    operatingHours: "17:30 - 22:00",
    isOpen: true,
    theme: "michelin",
  },
  {
    id: 103,
    name: "한식 파인다이닝",
    category: "korean",
    rating: 4.7,
    reviewCount: 378,
    address: "서울 종로구 삼청동 789",
    imageUrl: "https://picsum.photos/seed/michelin3/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "michelin",
  },
  {
    id: 104,
    name: "이탈리안 키친",
    category: "western",
    rating: 4.8,
    reviewCount: 289,
    address: "서울 강남구 신사동 012",
    imageUrl: "https://picsum.photos/seed/michelin4/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "michelin",
  },
  {
    id: 105,
    name: "중식 파인다이닝",
    category: "chinese",
    rating: 4.7,
    reviewCount: 245,
    address: "서울 중구 을지로 345",
    imageUrl: "https://picsum.photos/seed/michelin5/400/300",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "michelin",
  },

  // SNS 인기 맛집
  {
    id: 201,
    name: "인스타 디저트 카페",
    category: "dessert",
    rating: 4.6,
    reviewCount: 1245,
    address: "서울 마포구 연남동 123",
    imageUrl: "https://picsum.photos/seed/sns1/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "sns",
  },
  {
    id: 202,
    name: "포토제닉 브런치",
    category: "western",
    rating: 4.5,
    reviewCount: 982,
    address: "서울 용산구 이태원동 456",
    imageUrl: "https://picsum.photos/seed/sns2/400/300",
    priceRange: "₩₩",
    operatingHours: "10:00 - 20:00",
    isOpen: true,
    theme: "sns",
  },
  {
    id: 203,
    name: "핑크 카페",
    category: "dessert",
    rating: 4.4,
    reviewCount: 876,
    address: "서울 강남구 가로수길 789",
    imageUrl: "https://picsum.photos/seed/sns3/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "sns",
  },
  {
    id: 204,
    name: "루프탑 레스토랑",
    category: "western",
    rating: 4.5,
    reviewCount: 654,
    address: "서울 용산구 한남동 012",
    imageUrl: "https://picsum.photos/seed/sns4/400/300",
    priceRange: "₩₩₩",
    operatingHours: "17:00 - 23:00",
    isOpen: true,
    theme: "sns",
  },
  {
    id: 205,
    name: "플라워 카페",
    category: "dessert",
    rating: 4.3,
    reviewCount: 543,
    address: "서울 성동구 성수동 345",
    imageUrl: "https://picsum.photos/seed/sns5/400/300",
    priceRange: "₩₩",
    operatingHours: "11:00 - 20:00",
    isOpen: true,
    theme: "sns",
  },

  // 데이트 맛집
  {
    id: 301,
    name: "와인 다이닝",
    category: "western",
    rating: 4.7,
    reviewCount: 432,
    address: "서울 강남구 청담동 123",
    imageUrl: "https://picsum.photos/seed/date1/400/300",
    priceRange: "₩₩₩",
    operatingHours: "17:00 - 23:00",
    isOpen: true,
    theme: "date",
  },
  {
    id: 302,
    name: "이탈리안 트라토리아",
    category: "western",
    rating: 4.6,
    reviewCount: 387,
    address: "서울 서초구 반포동 456",
    imageUrl: "https://picsum.photos/seed/date2/400/300",
    priceRange: "₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "date",
  },
  {
    id: 303,
    name: "스테이크 하우스",
    category: "western",
    rating: 4.8,
    reviewCount: 345,
    address: "서울 강남구 압구정동 789",
    imageUrl: "https://picsum.photos/seed/date3/400/300",
    priceRange: "₩₩₩",
    operatingHours: "17:00 - 22:00",
    isOpen: true,
    theme: "date",
  },
  {
    id: 304,
    name: "프렌치 비스트로",
    category: "western",
    rating: 4.5,
    reviewCount: 298,
    address: "서울 용산구 이태원동 012",
    imageUrl: "https://picsum.photos/seed/date4/400/300",
    priceRange: "₩₩",
    operatingHours: "17:30 - 23:00",
    isOpen: true,
    theme: "date",
  },
  {
    id: 305,
    name: "스시 오마카세",
    category: "japanese",
    rating: 4.9,
    reviewCount: 276,
    address: "서울 강남구 신사동 345",
    imageUrl: "https://picsum.photos/seed/date5/400/300",
    priceRange: "₩₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "date",
  },

  // 현지인 추천 맛집
  {
    id: 401,
    name: "할매국수",
    category: "korean",
    rating: 4.5,
    reviewCount: 876,
    address: "서울 종로구 종로3가 123",
    imageUrl: "https://picsum.photos/seed/local1/400/300",
    priceRange: "₩",
    operatingHours: "10:30 - 21:00",
    isOpen: true,
    theme: "local",
  },
  {
    id: 402,
    name: "원조 김밥",
    category: "korean",
    rating: 4.3,
    reviewCount: 654,
    address: "서울 중구 을지로 456",
    imageUrl: "https://picsum.photos/seed/local2/400/300",
    priceRange: "₩",
    operatingHours: "06:00 - 20:00",
    isOpen: true,
    theme: "local",
  },
  {
    id: 403,
    name: "시장 칼국수",
    category: "korean",
    rating: 4.4,
    reviewCount: 543,
    address: "서울 동대문구 제기동 789",
    imageUrl: "https://picsum.photos/seed/local3/400/300",
    priceRange: "₩",
    operatingHours: "09:00 - 21:00",
    isOpen: true,
    theme: "local",
  },
  {
    id: 404,
    name: "골목 냉면",
    category: "korean",
    rating: 4.6,
    reviewCount: 432,
    address: "서울 용산구 용산동 012",
    imageUrl: "https://picsum.photos/seed/local4/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "local",
  },
  {
    id: 405,
    name: "시장 떡볶이",
    category: "korean",
    rating: 4.2,
    reviewCount: 321,
    address: "서울 광진구 자양동 345",
    imageUrl: "https://picsum.photos/seed/local5/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 22:00",
    isOpen: true,
    theme: "local",
  },

  // 가성비 맛집
  {
    id: 501,
    name: "백반집",
    category: "korean",
    rating: 4.3,
    reviewCount: 765,
    address: "서울 중구 명동 123",
    imageUrl: "https://picsum.photos/seed/value1/400/300",
    priceRange: "₩",
    operatingHours: "06:00 - 20:00",
    isOpen: true,
    theme: "value",
  },
  {
    id: 502,
    name: "중국집",
    category: "chinese",
    rating: 4.2,
    reviewCount: 543,
    address: "서울 동대문구 휘경동 456",
    imageUrl: "https://picsum.photos/seed/value2/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "value",
  },
  {
    id: 503,
    name: "돈까스집",
    category: "japanese",
    rating: 4.4,
    reviewCount: 432,
    address: "서울 관악구 봉천동 789",
    imageUrl: "https://picsum.photos/seed/value3/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "value",
  },
  {
    id: 504,
    name: "분식집",
    category: "korean",
    rating: 4.1,
    reviewCount: 321,
    address: "서울 동작구 상도동 012",
    imageUrl: "https://picsum.photos/seed/value4/400/300",
    priceRange: "₩",
    operatingHours: "10:30 - 21:30",
    isOpen: true,
    theme: "value",
  },
  {
    id: 505,
    name: "부대찌개",
    category: "korean",
    rating: 4.3,
    reviewCount: 234,
    address: "서울 마포구 공덕동 345",
    imageUrl: "https://picsum.photos/seed/value5/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 22:00",
    isOpen: true,
    theme: "value",
  },

  // 대만인이 많이 찾는 맛집
  {
    id: 601,
    name: "샤브샤브 전문점",
    category: "chinese",
    rating: 4.6,
    reviewCount: 432,
    address: "서울 중구 명동 123",
    imageUrl: "https://picsum.photos/seed/taiwan1/400/300",
    priceRange: "₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "taiwan",
  },
  {
    id: 602,
    name: "마라탕 맛집",
    category: "chinese",
    rating: 4.5,
    reviewCount: 345,
    address: "서울 서대문구 신촌동 456",
    imageUrl: "https://picsum.photos/seed/taiwan2/400/300",
    priceRange: "₩",
    operatingHours: "11:00 - 22:00",
    isOpen: true,
    theme: "taiwan",
  },
  {
    id: 603,
    name: "대만식 디저트",
    category: "dessert",
    rating: 4.4,
    reviewCount: 287,
    address: "서울 마포구 홍대입구 789",
    imageUrl: "https://picsum.photos/seed/taiwan3/400/300",
    priceRange: "₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "taiwan",
  },
  {
    id: 604,
    name: "훠궈 전문점",
    category: "chinese",
    rating: 4.7,
    reviewCount: 234,
    address: "서울 강남구 역삼동 012",
    imageUrl: "https://picsum.photos/seed/taiwan4/400/300",
    priceRange: "₩₩",
    operatingHours: "17:00 - 23:00",
    isOpen: true,
    theme: "taiwan",
  },
  {
    id: 605,
    name: "버블티 카페",
    category: "dessert",
    rating: 4.3,
    reviewCount: 198,
    address: "서울 서초구 방배동 345",
    imageUrl: "https://picsum.photos/seed/taiwan5/400/300",
    priceRange: "₩",
    operatingHours: "10:00 - 22:00",
    isOpen: true,
    theme: "taiwan",
  },
];
