export const MOCK_SEARCH_KEYWORDS = [
  "한식",
  "미슐랭 맛집",
  "대만인이 많이 찾는 맛집",
  "SNS 핫플레이스",
  "데이트 코스",
  "가성비 맛집",
];

// 테마 뱃지 정의
export const THEMES = [
  { label: "백종원 맛집", slug: "baek" },
  { label: "흑백요리사 맛집", slug: "chef" },
  { label: "성시경 맛집", slug: "sung" },
] as const;

// 레스토랑 테마 정의
export const MOCK_RESTAURANT_THEMES = [
  {
    id: 1,
    title: "미슐랭 가이드 선정 맛집",
    imageUrl: "/images/restaurants/korean-1.png",
    slug: "michelin",
  },
  {
    id: 2,
    title: "SNS에서 인기 있는 맛집",
    imageUrl: "/images/restaurants/korean-2.png",
    slug: "sns",
  },
  {
    id: 3,
    title: "데이트하기 좋은 맛집",
    imageUrl: "/images/restaurants/korean-3.png",
    slug: "date",
  },
  {
    id: 4,
    title: "현지인이 추천하는 맛집",
    imageUrl: "/images/restaurants/korean-4.png",
    slug: "local",
  },
  {
    id: 5,
    title: "가성비 좋은 맛집",
    imageUrl: "/images/restaurants/korean-5.png",
    slug: "value",
  },
  {
    id: 6,
    title: "대만인이 많이 찾는 맛집",
    imageUrl: "/images/restaurants/korean-6.png",
    slug: "taiwan",
  },
];

export interface Restaurant {
  id: number;
  name: string;
  description: string;
  category: string;
  rating: number;
  reviewCount: number;
  address: string;
  imageUrl: string;
  priceRange: string;
  operatingHours: string;
  isOpen: boolean;
  theme?: string;
  latitude: number;
  longitude: number;
  tags: string[];
  phoneNumber?: string;
  snsUrl?: string;
}

export const MOCK_RESTAURANTS: Restaurant[] = [
  // 한식 (korean)
  {
    id: 1,
    name: "원조 백종원의 찜닭",
    description: "백종원이 추천하는 찜닭의 정석",
    imageUrl: "/images/restaurants/korean-1.png",
    category: "korean",
    rating: 4.7,
    reviewCount: 312,
    address: "서울 종로구 인사동 789",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "baek",
    latitude: 37.5718,
    longitude: 126.9858,
    tags: [
      "데이트하기 좋은",
      "분위기 좋은",
      "가성비가 좋은",
      "인스타감성",
      "조용한",
    ],
    phoneNumber: "02-123-4567",
    snsUrl: "https://www.instagram.com/baekjongwon",
  },
  {
    id: 2,
    name: "흑백요리사의 파스타",
    description: "흑백요리사가 직접 개발한 레시피",
    imageUrl: "/images/restaurants/korean-2.png",
    category: "italian",
    rating: 4.9,
    reviewCount: 458,
    address: "서울 종로구 삼청동 123",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:30",
    isOpen: true,
    theme: "chef",
    latitude: 37.5825,
    longitude: 126.9814,
    tags: ["파스타", "이탈리안", "분위기 좋은"],
    phoneNumber: "02-234-5678",
  },
  {
    id: 3,
    name: "성시경의 면요리",
    description: "성시경이 극찬한 평양냉면 맛집",
    imageUrl: "/images/restaurants/korean-3.png",
    category: "korean",
    rating: 4.5,
    reviewCount: 221,
    address: "서울 중구 을지로 456",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "sung",
    latitude: 37.5662,
    longitude: 126.9785,
    tags: ["면요리", "평양냉면", "24시간"],
    phoneNumber: "02-345-6789",
  },
  {
    id: 4,
    name: "K-Street Food",
    description: "Popular street food dishes in a cozy setting.",
    imageUrl: "/images/restaurants/korean-4.png",
    category: "korean",
    rating: 4.8,
    reviewCount: 534,
    address: "서울 종로구 청운동 789",
    priceRange: "₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "korean",
    latitude: 37.5866,
    longitude: 126.9687,
    tags: ["길거리음식", "분위기 좋은", "가성비"],
    phoneNumber: "02-456-7890",
  },
  {
    id: 5,
    name: "평양냉면",
    description: "Traditional Korean cold noodles.",
    imageUrl: "/images/restaurants/korean-5.png",
    category: "korean",
    rating: 4.6,
    reviewCount: 178,
    address: "서울 중구 명동 234",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "korean",
    latitude: 37.5634,
    longitude: 126.985,
    tags: ["냉면", "평양냉면", "전통한식"],
    phoneNumber: "02-567-8901",
  },

  // 중식 (chinese)
  {
    id: 6,
    name: "대만반점",
    description: "Authentic Taiwanese cuisine in a traditional setting.",
    imageUrl: "/images/restaurants/chinese-1.png",
    category: "chinese",
    rating: 4.5,
    reviewCount: 95,
    address: "서울 마포구 연남동 456",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:30",
    isOpen: true,
    theme: "chinese",
    latitude: 37.5612,
    longitude: 126.9249,
    tags: [],
    phoneNumber: "02-678-9012",
  },
  {
    id: 7,
    name: "홍콩반점",
    description: "Authentic Hong Kong cuisine in a traditional setting.",
    imageUrl: "/images/restaurants/chinese-2.png",
    category: "chinese",
    rating: 4.3,
    reviewCount: 167,
    address: "서울 서대문구 연희동 789",
    priceRange: "₩",
    operatingHours: "11:00 - 22:00",
    isOpen: true,
    theme: "chinese",
    latitude: 37.5687,
    longitude: 126.9341,
    tags: [],
    phoneNumber: "02-789-0123",
  },
  {
    id: 8,
    name: "취향관",
    description: "Traditional Chinese cuisine in a modern setting.",
    imageUrl: "/images/restaurants/chinese-3.png",
    category: "chinese",
    rating: 4.7,
    reviewCount: 423,
    address: "서울 중구 명동 567",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
    theme: "chinese",
    latitude: 37.5641,
    longitude: 126.9862,
    tags: [],
    phoneNumber: "02-890-1234",
  },
  {
    id: 9,
    name: "마라훠궈",
    description: "Spicy Sichuan cuisine in a modern setting.",
    imageUrl: "/images/restaurants/chinese-4.png",
    category: "chinese",
    rating: 4.6,
    reviewCount: 312,
    address: "서울 마포구 상수동 890",
    priceRange: "₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "chinese",
    latitude: 37.5476,
    longitude: 126.9235,
    tags: [],
    phoneNumber: "02-901-2345",
  },
  {
    id: 10,
    name: "딤섬하우스",
    description: "Traditional Chinese cuisine in a modern setting.",
    imageUrl: "/images/restaurants/chinese-5.png",
    category: "chinese",
    rating: 4.4,
    reviewCount: 178,
    address: "서울 강남구 신사동 123",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "chinese",
    latitude: 37.5236,
    longitude: 127.0214,
    tags: [],
    phoneNumber: "02-012-3456",
  },

  // 일식 (japanese)
  {
    id: 11,
    name: "미도인 - 미슐랭 1스타",
    description: "Michelin-starred Japanese restaurant.",
    imageUrl: "/images/restaurants/japanese-1.png",
    category: "japanese",
    rating: 4.8,
    reviewCount: 128,
    address: "서울 중구 을지로 123",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
    theme: "japanese",
    latitude: 37.5657,
    longitude: 126.9892,
    tags: [],
    phoneNumber: "02-123-4567",
  },
  {
    id: 12,
    name: "스시히로",
    description: "Sushi restaurant with a modern twist.",
    imageUrl: "/images/restaurants/japanese-2.png",
    category: "japanese",
    rating: 4.9,
    reviewCount: 245,
    address: "서울 강남구 청담동 456",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 22:00",
    isOpen: true,
    theme: "japanese",
    latitude: 37.5245,
    longitude: 127.0431,
    tags: [],
    phoneNumber: "02-234-5678",
  },
  {
    id: 13,
    name: "라멘베이스",
    description: "Japanese ramen restaurant with a modern twist.",
    imageUrl: "/images/restaurants/japanese-3.png",
    category: "japanese",
    rating: 4.5,
    reviewCount: 567,
    address: "서울 마포구 합정동 789",
    priceRange: "₩",
    operatingHours: "11:00 - 21:30",
    isOpen: true,
    theme: "japanese",
    latitude: 37.5492,
    longitude: 126.9156,
    tags: [],
    phoneNumber: "02-345-6789",
  },
  {
    id: 14,
    name: "돈카츠 전문점",
    description: "Japanese tonkatsu restaurant.",
    imageUrl: "/images/restaurants/japanese-4.png",
    category: "japanese",
    rating: 4.6,
    reviewCount: 432,
    address: "서울 서초구 방배동 012",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "japanese",
    latitude: 37.4824,
    longitude: 126.9912,
    tags: [],
    phoneNumber: "02-456-7890",
  },
  {
    id: 15,
    name: "우동야",
    description: "Japanese udon restaurant with a modern twist.",
    imageUrl: "/images/restaurants/japanese-5.png",
    category: "japanese",
    rating: 4.4,
    reviewCount: 198,
    address: "서울 송파구 잠실동 345",
    priceRange: "₩",
    operatingHours: "10:30 - 21:00",
    isOpen: true,
    theme: "japanese",
    latitude: 37.5138,
    longitude: 127.0857,
    tags: [],
    phoneNumber: "02-567-8901",
  },

  // 디저트 (dessert)
  {
    id: 16,
    name: "디저트 천국",
    description: "Heavenly desserts in a cozy setting.",
    imageUrl: "/images/restaurants/dessert-1.png",
    category: "dessert",
    rating: 4.9,
    reviewCount: 445,
    address: "서울 강남구 신사동 567",
    priceRange: "₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "dessert",
    latitude: 37.5216,
    longitude: 127.0201,
    tags: [],
    phoneNumber: "02-678-9012",
  },
  {
    id: 17,
    name: "마카롱 하우스",
    description: "Macaron cafe with a modern twist.",
    imageUrl: "/images/restaurants/dessert-2.png",
    category: "dessert",
    rating: 4.7,
    reviewCount: 334,
    address: "서울 마포구 연남동 678",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "dessert",
    latitude: 37.5605,
    longitude: 126.9241,
    tags: [],
    phoneNumber: "02-789-0123",
  },
  {
    id: 18,
    name: "초콜릿 카페",
    description: "Chocolate cafe with a modern twist.",
    imageUrl: "/images/restaurants/dessert-3.png",
    category: "dessert",
    rating: 4.8,
    reviewCount: 223,
    address: "서울 용산구 이태원동 890",
    priceRange: "₩₩",
    operatingHours: "12:00 - 21:00",
    isOpen: true,
    theme: "dessert",
    latitude: 37.5347,
    longitude: 126.9941,
    tags: [],
    phoneNumber: "02-890-1234",
  },
  {
    id: 19,
    name: "타르트 & 케이크",
    description: "Tart and cake cafe with a modern twist.",
    imageUrl: "/images/restaurants/dessert-4.png",
    category: "dessert",
    rating: 4.6,
    reviewCount: 167,
    address: "서울 서초구 반포동 123",
    priceRange: "₩₩",
    operatingHours: "11:00 - 20:00",
    isOpen: true,
    theme: "dessert",
    latitude: 37.5038,
    longitude: 127.0124,
    tags: [],
    phoneNumber: "02-901-2345",
  },
  {
    id: 20,
    name: "젤라또 랩",
    description: "Gelato cafe with a modern twist.",
    imageUrl: "/images/restaurants/dessert-5.png",
    category: "dessert",
    rating: 4.5,
    reviewCount: 198,
    address: "서울 종로구 삼청동 456",
    priceRange: "₩",
    operatingHours: "12:00 - 21:00",
    isOpen: true,
    theme: "dessert",
    latitude: 37.5814,
    longitude: 126.9816,
    tags: [],
    phoneNumber: "02-012-3456",
  },

  // 24시간 운영 (24-hours)
  {
    id: 21,
    name: "심야식당",
    description: "24-hour restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/24hours-1.png",
    category: "24-hours",
    rating: 4.4,
    reviewCount: 89,
    address: "서울 마포구 서교동 890",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "24-hours",
    latitude: 37.5526,
    longitude: 126.9218,
    tags: [],
    phoneNumber: "02-123-4567",
  },
  {
    id: 22,
    name: "올나잇 포차",
    description: "24-hour cafe serving coffee and desserts.",
    imageUrl: "/images/restaurants/24hours-2.png",
    category: "24-hours",
    rating: 4.3,
    reviewCount: 156,
    address: "서울 강남구 역삼동 234",
    priceRange: "₩₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "24-hours",
    latitude: 37.5012,
    longitude: 127.0359,
    tags: [],
    phoneNumber: "02-234-5678",
  },
  {
    id: 23,
    name: "새벽집",
    description: "24-hour restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/24hours-3.png",
    category: "24-hours",
    rating: 4.5,
    reviewCount: 234,
    address: "서울 용산구 한남동 567",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "24-hours",
    latitude: 37.5352,
    longitude: 127.0016,
    tags: [],
    phoneNumber: "02-345-6789",
  },
  {
    id: 24,
    name: "야간식당",
    description: "24-hour restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/24hours-4.png",
    category: "24-hours",
    rating: 4.2,
    reviewCount: 167,
    address: "서울 중구 을지로 890",
    priceRange: "₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "24-hours",
    latitude: 37.5657,
    longitude: 126.9912,
    tags: [],
    phoneNumber: "02-456-7890",
  },
  {
    id: 25,
    name: "밤하늘",
    description: "24-hour restaurant with a modern twist.",
    imageUrl: "/images/restaurants/24hours-5.png",
    category: "24-hours",
    rating: 4.6,
    reviewCount: 145,
    address: "서울 동대문구 청량리동 123",
    priceRange: "₩₩",
    operatingHours: "24시간",
    isOpen: true,
    theme: "24-hours",
    latitude: 37.5805,
    longitude: 127.0478,
    tags: [],
    phoneNumber: "02-567-8901",
  },

  // 비건/채식 (vegan)
  {
    id: 26,
    name: "베지테리안",
    description: "Vegan restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/vegan-1.png",
    category: "vegan",
    rating: 4.6,
    reviewCount: 67,
    address: "서울 용산구 이태원동 234",
    priceRange: "₩₩₩",
    operatingHours: "10:00 - 22:00",
    isOpen: true,
    theme: "vegan",
    latitude: 37.5342,
    longitude: 126.9945,
    tags: [],
    phoneNumber: "02-678-9012",
  },
  {
    id: 27,
    name: "그린테이블",
    description: "Vegan restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/vegan-2.png",
    category: "vegan",
    rating: 4.7,
    reviewCount: 189,
    address: "서울 마포구 상수동 567",
    priceRange: "₩₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "vegan",
    latitude: 37.5478,
    longitude: 126.9231,
    tags: [],
    phoneNumber: "02-789-0123",
  },
  {
    id: 28,
    name: "로푸드 카페",
    description: "Vegan cafe serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/vegan-3.png",
    category: "vegan",
    rating: 4.5,
    reviewCount: 134,
    address: "서울 강남구 청담동 890",
    priceRange: "₩₩",
    operatingHours: "09:00 - 20:00",
    isOpen: true,
    theme: "vegan",
    latitude: 37.5241,
    longitude: 127.0428,
    tags: [],
    phoneNumber: "02-890-1234",
  },
  {
    id: 29,
    name: "채식주의",
    description: "Vegan restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/vegan-4.png",
    category: "vegan",
    rating: 4.8,
    reviewCount: 223,
    address: "서울 서초구 방배동 123",
    priceRange: "₩₩₩",
    operatingHours: "11:30 - 21:00",
    isOpen: true,
    theme: "vegan",
    latitude: 37.4821,
    longitude: 126.9915,
    tags: [],
    phoneNumber: "02-901-2345",
  },
  {
    id: 30,
    name: "비건 키친",
    description: "Vegan restaurant serving traditional Korean dishes.",
    imageUrl: "/images/restaurants/vegan-5.png",
    category: "vegan",
    rating: 4.4,
    reviewCount: 156,
    address: "서울 성동구 성수동 456",
    priceRange: "₩₩",
    operatingHours: "11:00 - 20:30",
    isOpen: true,
    theme: "vegan",
    latitude: 37.5425,
    longitude: 127.0558,
    tags: [],
    phoneNumber: "02-012-3456",
  },
];

export const MOCK_THEME_RESTAURANTS: Restaurant[] = [
  {
    id: 101,
    name: "스타 다이닝",
    description: "Michelin-starred Korean restaurant.",
    imageUrl: "/images/restaurants/michelin-1.png",
    category: "korean",
    rating: 4.9,
    reviewCount: 521,
    address: "서울 강남구 청담동 123",
    priceRange: "₩₩₩₩",
    operatingHours: "12:00 - 22:00",
    isOpen: true,
    theme: "michelin",
    latitude: 37.5248,
    longitude: 127.0432,
    tags: ["미슐랭", "고급", "데이트"],
    phoneNumber: "02-345-6789",
    snsUrl: "https://www.instagram.com/stardining",
  },
  {
    id: 102,
    name: "인스타 카페",
    description: "SNS cafe with a modern twist.",
    imageUrl: "/images/restaurants/sns-1.png",
    category: "dessert",
    rating: 4.7,
    reviewCount: 832,
    address: "서울 용산구 이태원동 456",
    priceRange: "₩₩",
    operatingHours: "10:00 - 22:00",
    isOpen: true,
    theme: "sns",
    latitude: 37.5345,
    longitude: 126.9942,
    tags: ["인스타", "카페", "디저트"],
    phoneNumber: "02-456-7890",
  },
  {
    id: 103,
    name: "로맨틱 가든",
    description: "Romantic Italian restaurant with a modern twist.",
    imageUrl: "/images/restaurants/date-1.png",
    category: "italian",
    rating: 4.8,
    reviewCount: 423,
    address: "서울 서초구 반포동 789",
    priceRange: "₩₩₩",
    operatingHours: "17:00 - 23:00",
    isOpen: true,
    theme: "date",
    latitude: 37.5035,
    longitude: 127.0121,
    tags: [],
    phoneNumber: "02-567-8901",
  },
  {
    id: 104,
    name: "시장통 맛집",
    description: "Traditional Korean dishes in a modern setting.",
    imageUrl: "/images/restaurants/local-1.png",
    category: "korean",
    rating: 4.6,
    reviewCount: 1243,
    address: "서울 종로구 광장시장 123",
    priceRange: "₩",
    operatingHours: "10:30 - 20:00",
    isOpen: true,
    theme: "local",
    latitude: 37.5701,
    longitude: 126.9987,
    tags: [],
    phoneNumber: "02-678-9012",
  },
  {
    id: 105,
    name: "착한식당",
    description: "Traditional Korean dishes with a modern twist.",
    imageUrl: "/images/restaurants/value-1.png",
    category: "korean",
    rating: 4.5,
    reviewCount: 932,
    address: "서울 관악구 봉천동 456",
    priceRange: "₩",
    operatingHours: "11:00 - 21:00",
    isOpen: true,
    theme: "value",
    latitude: 37.4812,
    longitude: 126.9528,
    tags: [],
    phoneNumber: "02-789-0123",
  },
  {
    id: 106,
    name: "타이베이 키친",
    description: "Traditional Chinese cuisine in a modern setting.",
    imageUrl: "/images/restaurants/taiwan-1.png",
    category: "chinese",
    rating: 4.7,
    reviewCount: 345,
    address: "서울 중구 명동 789",
    priceRange: "₩₩",
    operatingHours: "11:30 - 21:30",
    isOpen: true,
    theme: "taiwan",
    latitude: 37.5638,
    longitude: 126.9852,
    tags: [],
    phoneNumber: "02-890-1234",
  },
];

export function getRestaurantById(id: string): Restaurant | undefined {
  // 모든 레스토랑 데이터를 합칩니다
  const allRestaurants: Restaurant[] = [
    ...MOCK_RESTAURANTS,
    ...MOCK_THEME_RESTAURANTS,
  ];
  return allRestaurants.find((r) => r.id === parseInt(id, 10));
}
